# Production
# Redis & postgres are not listed here as containers as we use AWS ElastiCache - Redis & RDS - Postgres as separate services in prod
# and connect them to our AWS ElasticBeanstalk instance(which runs the docker containers below) through a Security Group
# All env vars like PG_USER, REDIS_HOST etc below should be entered in AWS environment properties section

version: "3"
services:
  client:
    image: "tzetzo/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "tzetzo/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
  worker:
    image: "tzetzo/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "tzetzo/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"