name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tzetzo/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tzetzo/react-test npm test

      - run: docker build -t tzetzo/multi-client ./client
      - run: docker build -t tzetzo/multi-nginx ./nginx
      - run: docker build -t tzetzo/multi-server ./server
      - run: docker build -t tzetzo/multi-worker ./worker

      - run: docker push tzetzo/multi-client
      - run: docker push tzetzo/multi-nginx
      - run: docker push tzetzo/multi-server
      - run: docker push tzetzo/multi-worker
